### ISSUE TITLE
StatusCode 495

### ISSUE THREAD

**Issue by Jumagick** [diev/Api5704#1]
Добрый день,
Только начинаю проект по 5704-У и разбираюсь с TLS.
С НБКИ квест по сертификатам прошел и сертификат они мой себе подгрузили.
Через Yandex brawser я теперь на https://reports.demo.nbki.ru/qbch/ могу зайти и ошибку 495 перестал получать.

Запрос через Api5704 возвращает ответ 495 (проблемы с шифрованием и сертификатами) - правильно ли я понимаю, что это связано с тем, что у меня не используется ГОСТ шифрование на уровне TLS.
КриптоПро CPS с лицензией на TLS клиент установлена.
Почему с TLS проблема пока не могу понять.

**Comment by Jumagick** [comment]
Проблема была на стороне НБКИ, просто сертификат на тестовый сервер не подгрузили.

**Comment by diev** [comment]
Типичная для них ситуация, что для нас - ошибка.

**Comment by diev** [comment]
Типичная для них ситуация, что для нас выходит как ошибка.
